apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biblioteka

resources:
  - namespace.yaml
  - postgres.yaml
  - eureka-server.yaml
  - gateway-service.yaml
  - user-service.yaml
  - library-management-service.yaml
  - loan-management-service.yaml
  - seat-management-service.yaml
  - ui-service.yaml
  - ingress.yaml

configMapGenerator:
  - name: biblioteka-config
    envs:
      - config.env
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: biblioteka-secrets
    envs:
      - secrets.env
    options:
      disableNameSuffixHash: true

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: biblioteka

# 👇 FORCE THE LIBRARY SERVICE TO RUN PHYSICALLY ON WINDOWS
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: library-management-service
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/hostname: DESKTOP-CEEA6KT
    target:
      kind: Deployment
      name: library-management-service
